#[pytest]
#testpaths = tests
#python_files = test_*.py
#python_classes = Test*
#python_functions = test_*
#addopts = --html=reports/report.html --self-contained-html -v


[pytest]
testpaths = tests
addopts = --tb=short

markers =
    sanity: quick smoke checks after deployment
    regression: full validation suite before release
    bvt: build verification tests after every build
    unit: individual function level tests